export const INVERSIFY_TYPES = {
  Application: Symbol.for('Application'),
  ISubscriptionRepository: Symbol.for('ISubscriptionRepository'),
  ISubscriptionService: Symbol.for('ISubscriptionService'),
  ISubscriptionController: Symbol.for('ISubscriptionController'),
  IOpenExchangeApi: Symbol.for('IOpenExchangeApi'),
  IPrivatBankApi: Symbol.for('IPrivatBankApi'),
  ICurrencyService: Symbol.for('ICurrencyService'),
  IOpenExchangeStrategy: Symbol.for('IOpenExchangeStrategy'),
  IPrivatBankStrategy: Symbol.for('IPrivatBankStrategy'),
  ICurrencyStrategy: Symbol.for('ICurrencyStrategy'),
  ICurrencyController: Symbol.for('ICurrencyController'),
  IDatabaseService: Symbol.for('IDatabaseService'),
  IDotenvService: Symbol.for('IDotenvService'),
  INodemailerService: Symbol.for('INodemailerService'),
  INotifyRateCrone: Symbol.for('INotifyRateCrone'),
  ILoggerService: Symbol.for('ILoggerService'),
}