name: Linting

on: 
  push:
    branches:
        - "**"

jobs:

  run-commitlint-on-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.3

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint
